import assert from 'node:assert/strict'
import {
  categorizeCommits,
  formatReleaseNotes,
  parseArgs,
  parseConventionalCommit,
  parseGitLog,
  selectPreviousTag,
  semverTagValue,
} from '../scripts/release-notes.mjs'

assert.deepEqual(parseArgs(['--from', 'v1.0.0', '--to', 'HEAD', '--version', '1.2.1', '--output', 'notes.md']), {
  from: 'v1.0.0',
  to: 'HEAD',
  version: '1.2.1',
  output: 'notes.md',
  help: false,
})
assert.deepEqual(parseConventionalCommit('feat(pdf): render scanned pages'), {
  type: 'feat',
  scope: 'pdf',
  breaking: false,
  subject: 'render scanned pages',
})
assert.deepEqual(parseConventionalCommit('fix!: change upload protocol'), {
  type: 'fix',
  scope: undefined,
  breaking: true,
  subject: 'change upload protocol',
})
assert.equal(semverTagValue('v1.2.1'), '1.2.1')
assert.equal(semverTagValue('发行说明'), undefined)
assert.equal(selectPreviousTag(['v1.2.1', '发行说明', 'v1.0.0'], 'v1.2.1'), 'v1.0.0')

const commits = parseGitLog([
  'a'.repeat(40), 'feat(pdf): render scanned pages', 'A', 'a@example.com',
  'b'.repeat(40), 'fix: keep document bytes out of chat history', 'B', 'b@example.com',
  'c'.repeat(40), 'docs: explain automatic PDF fallback', 'C', 'c@example.com',
  'd'.repeat(40), 'chore: update dependency', 'D', 'd@example.com',
  'e'.repeat(40), 'miscellaneous maintenance', 'E', 'e@example.com',
  'f'.repeat(40), 'release: v1.2.0', 'F', 'f@example.com',
].map((field, index) => field + (index % 4 === 3 ? '\x1e' : '\x1f')).join(''))
const grouped = categorizeCommits(commits)
assert.equal(grouped.get('Features').length, 1)
assert.equal(grouped.get('Bug Fixes').length, 1)
assert.equal(grouped.get('Documentation').length, 1)
assert.equal(grouped.get('Maintenance').length, 1)
assert.equal(grouped.get('Other Changes').length, 1)

const notes = formatReleaseNotes({
  packageName: 'dsh-sfversion',
  version: '1.2.1',
  from: 'v1.2.0',
  commits,
  repositoryUrl: 'https://github.com/sparkmio/dsh-sfversion',
})
assert.match(notes, /## dsh-sfversion v1\.2\.1/)
assert.match(notes, /### Features/)
assert.match(notes, /render scanned pages/)
assert.match(notes, /https:\/\/github\.com\/sparkmio\/dsh-sfversion\/commit\/aaaaaaaa/)
assert.match(notes, /Generated by scripts\/release-notes\.mjs/)
assert.doesNotMatch(notes, /release: v1\.2\.0/)

console.log('release notes tests passed')
